// 只需要修改这个文件里的文字数据，不需要修改页面代码。
// "none" 表示尚未填写；progress 填 null，填写后改成 0 到 100 的数字。
window.LEARNING_DATA = {
  siteName: "向上学习",
  lastUpdated: "2026-07-30",

  student: {
    name: "杜同学",
    grade: "初二升初三",
    subjects: ["数学", "物理"],
    startDate: "2026-07-15",
    goal: "暑期衔接阶段：巩固初二知识，逐步建立初三数学与物理的学习节奏。",
  },

  lessons: [
    {
      date: "2026-07-30",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-30",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-29",
      subject: "数学",
      content: "根与系数的关系",
      problem: "公式不够熟练",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-29",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-28",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-28",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-27",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-27",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-23",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-23",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-22",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-22",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-21",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-21",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-20",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-20",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-17",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-17",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-16",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-16",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-15",
      subject: "数学",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
    {
      date: "2026-07-15",
      subject: "物理",
      content: "none",
      problem: "none",
      progress: null,
      evaluation: "none",
    },
  ],
};
